EXCHANGE_NAME = "astra"

QUEUE_ASTRO = "astra.astro"
QUEUE_PREDICTIONS = "astra.predictions"
QUEUE_NOTIFICATIONS = "astra.notifications"
QUEUE_COMPATIBILITY = "astra.compatibility"
QUEUE_REPORTS = "astra.reports"

ROUTING_NATAL_CHART = "natal_chart.generate"
ROUTING_DAILY_CONTEXT_BUILD = "daily_context.build"
ROUTING_PREDICTION_GENERATE = "prediction.generate"
ROUTING_PREDICTION_SEND = "prediction.send"
ROUTING_DAY_CARD_SEND = "day_card.send"
ROUTING_SYNASTRY_BUILD = "synastry.build"
ROUTING_COMPATIBILITY_GENERATE = "compatibility.generate"
ROUTING_PDF_GENERATE = "pdf.generate"
ROUTING_COMPATIBILITY_SEND = "compatibility.send"
ROUTING_NATAL_GENERATE = "natal_report.generate"
ROUTING_NATAL_PDF_GENERATE = "natal_report.pdf"
ROUTING_NATAL_SEND = "natal_report.send"
ROUTING_TAROT_READING_GENERATE = "tarot_reading.generate"
ROUTING_TAROT_READING_SEND = "tarot_reading.send"
ROUTING_ASK_ANSWER_GENERATE = "ask_answer.generate"
ROUTING_BROADCAST_SEND = "broadcast.send"
